[package]
name = "example_cartesian_product"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
core = { path = "./../core" }
dll_interface = { path = "./../dll_interface" }